export const dict = {
  // App name
  appName: 'BTP Manager',
  appSubtitle: 'تسيير ورش البناء',

  // Sidebar navigation
  nav: {
    dashboard: 'لوحة التحكم',
    companies: 'الشركات',
    clients: 'الزبناء',
    properties: 'العقارات',
    sales: 'المبيعات',
    projects: 'المشاريع',
    construction: 'تتبع الورش',
    suppliers: 'الموردين',
    intervenants: 'المتدخلين',
    commitments: 'الالتزامات',
    payments: 'الأداءات',
    expenses: 'المصاريف',
    reports: 'التقارير',
    admin: 'الإدارة',
    logout: 'الخروج',
  },

  // Actions
  actions: {
    new: 'زيد جديد',
    create: 'زيد',
    save: 'حفظ',
    edit: 'بدّل',
    update: 'حدّث',
    delete: 'حذف',
    archive: 'أرشف',
    restore: 'رجّع',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    close: 'غلق',
    back: 'رجوع',
    search: 'قلّب',
    filter: 'فلتر',
    upload: 'رفع',
    download: 'تحميل',
    export: 'تصدير',
    view: 'عاين',
    addPayment: 'زيد أداء',
    saving: 'كايحفظ...',
    loading: 'كيتحمّل...',
    deleting: 'كايحذف...',
    uploading: 'كايرفع...',
    exporting: 'كايصدر...',
  },

  // General labels
  labels: {
    name: 'الاسم',
    email: 'الإيميل',
    phone: 'الهاتف',
    address: 'العنوان',
    notes: 'ملاحظات',
    description: 'الوصف',
    date: 'التاريخ',
    status: 'الحالة',
    type: 'النوع',
    category: 'التصنيف',
    reference: 'المرجع',
    surface: 'المساحة',
    city: 'المدينة',
    ICE: 'ICE',
    CIN: 'CIN',
    RC: 'RC',
    id: 'المعرف',
    noData: 'ما كاين حتى معطى',
    noResults: 'ما كاين حتى نتيجة',
    confirmDelete: 'واش متأكد من الحذف؟',
    confirmAction: 'واش متأكد من هاد العملية؟',
    errorOccurred: 'وقع مشكل',
    success: 'تمت العملية بنجاح',
    required: 'إجباري',
    optional: 'اختياري',
    all: 'الكل',
    total: 'المجموع',
    count: 'العدد',
    actions: 'الإجراءات',
    information: 'المعلومات',
    generalInfo: 'معلومات عامة',
    financialInfo: 'معلومات مالية',
    createdAt: 'تاريخ الإنشاء',
    updatedAt: 'تاريخ التحديث',
    by: 'من طرف',
  },

  // Auth
  auth: {
    login: 'الدخول',
    loginTitle: 'مرحباً بك في BTP Manager',
    loginSubtitle: 'سيستيم تسيير ورش البناء',
    email: 'الإيميل',
    password: 'كلمة السر',
    signIn: 'دخول',
    loggingIn: 'كايدخل...',
    logout: 'الخروج',
    changePassword: 'بدّل كلمة السر',
    rememberMe: 'تذكرني',
    invalidCredentials: 'الإيميل أو كلمة السر غالطة',
    sessionExpired: 'انتهات الجلسة. أعاود الدخول من فضلك',
  },

  // Dashboard
  dashboard: {
    title: 'لوحة التحكم',
    totalProjects: 'مجموع المشاريع',
    totalSuppliers: 'مجموع الموردين',
    totalIntervenants: 'مجموع المتدخلين',
    totalCommitments: 'مجموع الالتزامات',
    totalPaid: 'مجموع المؤدى',
    totalRemaining: 'الباقي',
    totalExpenses: 'مجموع المصاريف',
    recentPayments: 'آخر الأداءات',
    outstandingCommitments: 'الالتزامات المتبقية',
    viewAll: 'عاين الكل',
    loading: 'كيتحمّل...',
  },

  // Companies
  companies: {
    title: 'الشركات',
    new: 'زيد شركة',
    edit: 'بدّل الشركة',
    detail: 'معلومات الشركة',
    name: 'الاسم',
    ICE: 'ICE',
    address: 'العنوان',
    phone: 'الهاتف',
    email: 'الإيميل',
    managerName: 'المسير',
    status: 'الحالة',
    active: 'نشيط',
    archived: 'مؤرشف',
    notes: 'ملاحظات',
    ownedProjects: 'المشاريع المملوكة',
    executingProjects: 'المشاريع المنفذة',
    noCompanies: 'ما كاين حتى شركة',
  },

  // Projects
  projects: {
    title: 'المشاريع',
    new: 'زيد مشروع',
    edit: 'بدّل المشروع',
    detail: 'تفاصيل المشروع',
    name: 'الاسم',
    city: 'المدينة',
    address: 'العنوان',
    description: 'الوصف',
    startDate: 'تاريخ البداية',
    expectedEndDate: 'تاريخ النهاية المتوقعة',
    actualEndDate: 'تاريخ النهاية الفعلي',
    projectType: 'نوع المشروع',
    ownershipType: 'نوع الملكية',
    ownerCompany: 'الشركة المالكة',
    executingCompany: 'الشركة المنفذة',
    externalClient: 'الزبناء الخارجيين',
    status: 'الحالة',
    active: 'نشيط',
    completed: 'سالي',
    onHold: 'واقف',
    cancelled: 'ملغى',
    notes: 'ملاحظات',
    financialSummary: 'الملخص المالي',
    totalCommitments: 'مجموع الالتزامات',
    totalPaid: 'مجموع المؤدى',
    totalRemaining: 'الباقي',
    totalExpenses: 'مجموع المصاريف',
    documents: 'الوثائق',
    construction: 'تتبع الورش',
    noProjects: 'ما كاين حتى مشروع',
    search: 'قلّب على المشاريع...',
    allStatuses: 'جميع الحالات',
  },

  // Suppliers
  suppliers: {
    title: 'الموردين',
    new: 'زيد مورد',
    edit: 'بدّل المورد',
    detail: 'تفاصيل المورد',
    name: 'الاسم',
    phone: 'الهاتف',
    category: 'التصنيف',
    status: 'الحالة',
    active: 'نشيط',
    archived: 'مؤرشف',
    notes: 'ملاحظات',
    financialSummary: 'الملخص المالي',
    totalCommitments: 'مجموع الالتزامات',
    totalPaid: 'مجموع المؤدى',
    totalRemaining: 'الباقي',
    noSuppliers: 'ما كاين حتى مورد',
  },

  // Intervenants
  intervenants: {
    title: 'المتدخلين',
    new: 'زيد متدخل',
    edit: 'بدّل المتدخل',
    detail: 'تفاصيل المتدخل',
    name: 'الاسم',
    phone: 'الهاتف',
    trade: 'الصنعة',
    status: 'الحالة',
    active: 'نشيط',
    archived: 'مؤرشف',
    notes: 'ملاحظات',
    financialSummary: 'الملخص المالي',
    totalCommitments: 'مجموع الالتزامات',
    totalPaid: 'مجموع المؤدى',
    totalRemaining: 'الباقي',
    noIntervenants: 'ما كاين حتى متدخل',
  },

  // Commitments
  commitments: {
    title: 'الالتزامات',
    new: 'زيد التزام',
    edit: 'بدّل الالتزام',
    detail: 'تفاصيل الالتزام',
    description: 'الوصف',
    agreedAmount: 'المبلغ المتفق عليه',
    commitmentDate: 'تاريخ الالتزام',
    beneficiaryType: 'نوع المستفيد',
    beneficiary: 'المستفيد',
    supplier: 'مورد',
    intervenant: 'متدخل',
    status: 'الحالة',
    open: 'مفتوح',
    paid: 'مؤدى',
    partiallyPaid: 'مؤدى جزئياً',
    cancelled: 'ملغى',
    notes: 'ملاحظات',
    balance: 'الحساب الباقي',
    remaining: 'الباقي',
    project: 'المشروع',
    noCommitments: 'ما كاين حتى التزام',
  },

  // Payments
  payments: {
    title: 'الأداءات',
    new: 'زيد أداء',
    edit: 'بدّل الأداء',
    detail: 'تفاصيل الأداء',
    amount: 'المبلغ',
    paymentDate: 'تاريخ الأداء',
    paymentMode: 'طريقة الأداء',
    cash: 'كاش',
    cheque: 'شيك',
    bankTransfer: 'تحويل بنكي',
    chequeNumber: 'رقم الشيك',
    beneficiary: 'المستفيد',
    beneficiaryType: 'نوع المستفيد',
    supplier: 'مورد',
    intervenant: 'متدخل',
    project: 'المشروع',
    commitment: 'الالتزام',
    notes: 'ملاحظات',
    noPayments: 'ما كاين حتى أداء',
  },

  // Expenses
  expenses: {
    title: 'المصاريف',
    new: 'زيد مصروف',
    edit: 'بدّل المصروف',
    detail: 'تفاصيل المصروف',
    description: 'الوصف',
    amount: 'المبلغ',
    expenseDate: 'تاريخ المصروف',
    category: 'التصنيف',
    paymentMode: 'طريقة الأداء',
    cash: 'كاش',
    cheque: 'شيك',
    bankTransfer: 'تحويل بنكي',
    project: 'المشروع',
    supplier: 'المورد',
    notes: 'ملاحظات',
    noExpenses: 'ما كاين حتى مصروف',
  },

  // Construction
  construction: {
    title: 'تتبع الورش',
    projectProgress: 'تقدم المشاريع',
    phases: 'المراحل',
    phase: 'المرحلة',
    progress: 'التقدم',
    progressPercentage: 'نسبة التقدم',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    status: 'الحالة',
    notStarted: 'ما بداش',
    inProgress: 'خدام',
    completed: 'سالي',
    blocked: 'واقف',
    validated: 'مصادق عليه',
    notes: 'ملاحظات',
    updateProgress: 'حدّث التقدم',
    noPhases: 'ما كاين حتى مرحلة',
    noProjects: 'ما كاين حتى مشروع',
  },

  // Documents
  documents: {
    title: 'الوثائق',
    upload: 'رفع وثيقة',
    uploadNew: 'رفع وثيقة جديدة',
    name: 'الاسم',
    originalName: 'الاسم الأصلي',
    category: 'التصنيف',
    size: 'الحجم',
    type: 'النوع',
    uploadDate: 'تاريخ الرفع',
    download: 'تحميل',
    delete: 'حذف',
    noDocuments: 'ما كاين حتى وثيقة',
    categories: {
      contract: 'العقد',
      invoice: 'فاتورة',
      report: 'تقرير',
      plan: 'مخطط',
      photo: 'صورة',
      other: 'آخر',
    },
    dropFile: 'أسقط الملف هنا أو إضغط للاختيار',
    maxSize: 'الحجم الأقصى: 20MB',
    uploading: 'كايرفع...',
    uploadSuccess: 'تم رفع الوثيقة بنجاح',
    dragAndDrop: 'أو إسحب وأسقط الملف هنا',
  },

  // Reports
  reports: {
    title: 'التقارير',
    projectReport: 'تقرير المشروع',
    supplierReport: 'تقرير المورد',
    intervenantReport: 'تقرير المتدخل',
    exportCSV: 'تصدير CSV',
    selectEntity: 'ختار العنصر',
    project: 'المشروع',
    supplier: 'المورد',
    intervenant: 'المتدخل',
    financialSummary: 'الملخص المالي',
    totalCommitments: 'مجموع الالتزامات',
    totalPaid: 'مجموع المؤدى',
    totalRemaining: 'الباقي',
    totalExpenses: 'مجموع المصاريف',
    exportSuccess: 'تم التصدير بنجاح',
    noData: 'ما كاين حتى معطى للتقرير',
  },

  // Clients
  clients: {
    title: 'الزبناء',
    new: 'زيد زبون',
    edit: 'بدّل الزبون',
    detail: 'تفاصيل الزبون',
    name: 'الاسم الكامل',
    phone: 'الهاتف',
    CIN: 'رقم البطاقة الوطنية',
    address: 'العنوان',
    notes: 'ملاحظات',
    projects: 'المشاريع',
    financialSummary: 'الملخص المالي',
    totalProjects: 'مجموع المشاريع',
    totalPayments: 'مجموع الأداءات',
    noClients: 'ما كاين حتى زبون',
  },

  // Properties (Real Estate)
  properties: {
    title: 'العقارات',
    new: 'زيد عقار',
    edit: 'بدّل العقار',
    detail: 'تفاصيل العقار',
    reference: 'المرجع',
    type: 'النوع',
    apartment: 'شقة',
    commercialSpace: 'محل تجاري',
    office: 'مكتب',
    warehouse: 'مخزن',
    surface: 'المساحة (م²)',
    price: 'الثمن (درهم)',
    project: 'المشروع',
    status: 'الحالة',
    available: 'متوفر',
    reserved: 'محجوز',
    sold: 'متباع',
    notes: 'ملاحظات',
    totalSold: 'مجموع المبيعات',
    noProperties: 'ما كاين حتى عقار',
  },

  // Sales
  sales: {
    title: 'المبيعات',
    new: 'زيد بيع',
    edit: 'بدّل البيع',
    detail: 'تفاصيل البيع',
    client: 'الزبون',
    property: 'العقار',
    salePrice: 'ثمن البيع (درهم)',
    downPayment: 'التسبيق (درهم)',
    saleDate: 'تاريخ البيع',
    status: 'الحالة',
    inProgress: 'في التقدم',
    completed: 'سالي',
    cancelled: 'ملغى',
    notes: 'ملاحظات',
    payments: 'الأداءات',
    addPayment: 'زيد أداء',
    totalPaid: 'مجموع المؤدى',
    remainingBalance: 'الحساب الباقي',
    financialSummary: 'الملخص المالي',
    noSales: 'ما كاين حتى بيع',
    noPayments: 'ما كاين حتى أداء',
    paymentDate: 'تاريخ الأداء',
    amount: 'المبلغ',
    deletePayment: 'حذف الأداء',
  },

  // Admin
  admin: {
    title: 'الإدارة',
    users: 'المستخدمين',
    roles: 'الصلاحيات',
    permissions: 'الرخص',
    newUser: 'زيد مستخدم',
    editUser: 'بدّل المستخدم',
    userDetail: 'تفاصيل المستخدم',
    fullName: 'الاسم الكامل',
    email: 'الإيميل',
    phone: 'الهاتف',
    password: 'كلمة السر',
    role: 'الصلاحية',
    status: 'الحالة',
    active: 'نشيط',
    inactive: 'غير نشيط',
    blocked: 'محظور',
    lastLogin: 'آخر دخول',
    noUsers: 'ما كاين حتى مستخدم',
    roleName: 'الصلاحية',
    roleCode: 'الكود',
    roleDescription: 'الوصف',
    permissionCode: 'كود الرخصة',
    permissionDescription: 'وصف الرخصة',
    noRoles: 'ما كاين حتى صلاحية',
    noPermissions: 'ما كاين حتى رخصة',
    confirmDeactivate: 'واش متأكد من تعطيل هاد المستخدم؟',
    confirmBlock: 'واش متأكد من حظر هاد المستخدم؟',
  },

  // Status badges
  status: {
    active: 'نشيط',
    inactive: 'غير نشيط',
    archived: 'مؤرشف',
    blocked: 'محظور',
    open: 'مفتوح',
    paid: 'مؤدى',
    partiallyPaid: 'مؤدى جزئياً',
    cancelled: 'ملغى',
    completed: 'سالي',
    inProgress: 'في التقدم',
    notStarted: 'ما بداش',
    onHold: 'واقف',
    available: 'متوفر',
    reserved: 'محجوز',
    sold: 'متباع',
    enCours: 'في التقدم',
    termine: 'سالي',
    annule: 'ملغى',
    dispo: 'متوفر',
    reserve: 'محجوز',
    vendu: 'متباع',
    yes: 'أيوه',
    no: 'لا',
  },

  // Financial labels
  financial: {
    totalCommitments: 'مجموع الالتزامات',
    totalPaid: 'مجموع المؤدى',
    totalRemaining: 'الباقي',
    totalExpenses: 'مجموع المصاريف',
    amount: 'المبلغ',
    agreedAmount: 'المبلغ المتفق عليه',
    remainingAmount: 'المبلغ الباقي',
    paymentMode: 'طريقة الأداء',
    cash: 'كاش',
    cheque: 'شيك',
    bankTransfer: 'تحويل بنكي',
    chequeNumber: 'رقم الشيك',
    balance: 'الحساب الباقي',
    salePrice: 'ثمن البيع',
    downPayment: 'التسبيق',
    totalPayments: 'مجموع الأداءات',
    remainingBalance: 'الحساب الباقي',
    unitPrice: 'ثمن الوحدة',
    quantity: 'الكمية',
    discount: 'الخصم',
    tax: 'الضريبة',
    taxNumber: 'رقم الضريبة',
    MAD: 'درهم',
  },

  // Construction phases
  phases: {
    terrain: 'دراسة الأرضية',
    fondations: 'الأساسات',
    infrastructure: 'البنية التحتية',
    grosOeuvre: 'الهيكل الخرساني',
    charpente: 'السقف والهيكل المعدني',
    couverture: 'التغطية',
    maçonnerie: 'البناء بالآجر',
    enduits: 'اللياسة',
    plomberie: 'السباكة',
    electricite: 'الكهرباء',
    menuiserie: 'النجارة',
    serrurerie: 'الحدادة',
    carrelage: 'البلاط',
    peinture: 'الدهان',
    revetements: 'التلبيس',
    cuisine: 'المطبخ',
    sanitaires: 'الحمامات',
    amenagementsExterieurs: 'التجهيزات الخارجية',
    finition: 'التشطيب',
  },

  // Errors
  errors: {
    generic: 'وقع مشكل. أعاود حاول.',
    network: 'مشكل في الاتصال بالإنترنت',
    notFound: 'العنصر ما كاينش',
    unauthorized: 'ما عندكش الصلاحية',
    forbidden: 'ما عندكش الحق',
    validation: 'المعطيات غالطة. قلب من فضلك.',
    required: 'هاد الخانة إجبارية',
    invalidEmail: 'الإيميل غالط',
    invalidPhone: 'رقم الهاتف غالط',
    minLength: 'الحد الأدنى هو {min} حروف',
    maxLength: 'الحد الأقصى هو {max} حروف',
    positiveNumber: 'القيمة خاصها تكون موجبة',
    deleteFailed: 'الحذف ما نجحش. أعاود حاول.',
    saveFailed: 'الحفظ ما نجحش. أعاود حاول.',
    loadFailed: 'التحميل ما نجحش. أعاود حاول.',
  },

  // Units
  units: {
    m2: 'م²',
    MAD: 'درهم',
    sqm: 'م²',
    percent: '%',
    kb: 'كيلوبايت',
    mb: 'ميغابايت',
    items: 'عنصر',
  },
};
